
# SEO settings
title: "Hello, World"
description: "Programming, coffee and travel."
keywords: ""
url: 
baseurl: 
# baseurl: null

google_analytics: 
repo: http://github.com/makeajourney/makeajourney.github.io
disqus_shortname: "fernandomoreira"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Soyoun Kim
  job      : University Student
  bio      : "always looking for the best project and good coffee."
  thumb    : /images/author.jpg
  email    : makeajourney@gmail.com
  url      : http://makeajourney.github.io
  github   : http://github.com/makeajourney
  twitter  : http://twitter.com/hacerunviaje
  facebook : http://facebook.com/makeajourney
  linkedin : http://linkedin.com/

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
